- id: '1567128610484'
  alias: Turn on the Lights at Sunset
  trigger:
  - event: sunset
    offset: -0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_porch_middle
    service: light.turn_on
  - data:
      entity_id: light.front_porch_outer
    service: light.turn_on
  - data:
      entity_id: light.garage_outside_lights
    service: light.turn_on
- id: '1567129231530'
  alias: Turn off the lights at Sunrise
  trigger:
  - event: sunrise
    offset: 0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_porch_middle
    service: light.turn_off
  - data:
      entity_id: light.front_porch_outer
    service: light.turn_off
  - data:
      entity_id: light.garage_outside_lights
    service: light.turn_off
- id: '1567133001615'
  alias: Wake Up
  trigger:
  - at: '6:30'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.mike_lamp
    service: light.turn_on
