- alias: Turn on the Lights at Sunset
  trigger:
  - event: sunset
    offset: -0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_porch_middle
    service: light.turn_on
  - data:
      entity_id: light.front_porch_outer
    service: light.turn_on
  - data:
      entity_id: light.garage_outside_lights
    service: light.turn_on
- alias: Turn off the lights at Sunrise
  trigger:
  - event: sunrise
    offset: 0:30
    platform: sun
  condition: []
  action:
  - data:
      entity_id: light.front_porch_middle
    service: light.turn_off
  - data:
      entity_id: light.front_porch_outer
    service: light.turn_off
  - data:
      entity_id: light.garage_outside_lights
    service: light.turn_off


- alias: Wake Up
  trigger:
  - at: '06:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: light.mike_lamp
    service: light.turn_on


- alias: 'Go to Work'
  trigger:
  - at: '07:30:00'
    platform: time
  condition: []
  action:
  - data:
      entity_id: group.all_lights
    service: light.turn_off
  - data:
      entity_id: group.all_fans
    service: fan.turn_off
