homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 298
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Lovelace UI
lovelace:
  mode: yaml

zone:
  - name: Home
    latitude: !secret home_latitude
    longitude: !secret home_longitude
    radius: 100
    icon: mdi:home

  - name: Work
    latitude: !secret work_latitude
    longitude: !secret work_longitude
    icon: mdi:briefcase

default_config:
#cloud:
#config:
frontend:
  themes: !include themes.yaml
#history:
  #exclude:
    #domains:
    #entities:
#logbook:
  #exclude:
    #domains:
    #entities:
#map:
#mobile_app:
#person:
#  - name: Mike
#    id: mike
#    user_id: mberkman
#    device_trackers:
#      - device_tracker.mberkman_pixel_3
#  - name: Leah
#    id: leah
#sun:
#system_health:
#updater:
#zeroconf:

discovery:
  #ignore:

hacs:
  token: !secret hacs_token

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  server_host: 127.0.0.1
  # Update this line to be your domain
  base_url: https://home.berkman.co
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1

##################################################################

# Ecovacs Deebot
ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: us
  continent: ww

# Google Assistant
google_assistant:
  project_id: !secret google_project_id
  api_key: !secret google_api_key
  secure_devices_pin: !secret google_secure_pin
  expose_by_default: false
  entity_config:
    group.upstairs_lights:
      expose: true
    cover.left_garage_door:
      expose: true
      room: Garage
    cover.middle_garage_door:
      expose: true
      room: Garage
    cover.right_garage_door:
      expose: true
      room: Garage
    fan.living_room_ceiling_fan:
      expose: false
      room: Living Room
    fan.master_bedroom_ceiling_fan:
      expose: false
      room: Master Bedroom
    fan.patio_ceiling_fan:
      expose: false
      room: Patio
    vacuum.deebot:
      expose: true
      room: Living Room

# IFTTT
ifttt:
  key: !secret ifttt_api_key

# Plex, Spotify and Vizio
media_player:
  - platform: spotify
    client_id: !secret spotify_client_id
    client_secret: !secret spotify_client_secret
    #aliases:
      #asdf: 'Something' 10.0.0.29
      #spotify_connect {'host': '10.0.0.29', 'port': 42332, 'hostname': 'a5f8003f-84d7-5d68-ae67-fb5550b-0.local.'}
      #spotify_connect {'host': '10.0.0.111', 'port': 41571, 'hostname': 'ccf5ebd4-eea3-545f-a844-17b0526-0.local.'}
      #spotify_connect {'host': '10.0.0.61', 'port': 34504, 'hostname': '214a1821-a60f-58c6-acd3-33ce045-0.local.'}
  - platform: plex
#  - platform: vizio
#    host: 10.0.0.25
#    device_class: soundbar

# IKEA Tradfri
tradfri:
  host: 10.0.0.71

# Liftmaster Garage Door Opener
cover:
  - platform: myq
    username: !secret liftmaster_username
    password: !secret liftmaster_password
    type: liftmaster

# Lutron Caseta
lutron_caseta_pro:
  bridges:
    - host: !secret lutron_caseta_pro_host
      mac: !secret lutron_caseta_pro_mac
      default_transition_seconds: 1.0
      # Note: Configure only switches, shades, and fans, all others will be dimmers
      fan: [ 4, 5, 9 ]

# MQTT
mqtt:
  discovery: true
  broker: soldier.cloudmqtt.com
  port: 24549
  username: !secret mqtt_username
  password: !secret mqtt_password

# Rachio Smart Irrigation
rachio:
  api_key: !secret rachio_api_key

# Roku
roku:
  - host: 10.0.0.111 #Living Room TV
  - host: 10.0.0.29 #Basement TV
  - host: 10.0.0.61 #Master Bedroom TV

sensor:
  - platform: plex
    host: 10.0.0.93
    port: 32400
    username: !secret plex_username
    password: !secret plex_password
    verify_ssl: false
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: google_wifi
    name: Google Wifi
  - platform: qnap
    host: 10.0.0.35
    username: !secret qnap_username
    password: !secret qnap_password
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used

tplink:
  discovery: false
  switch:
    - host: 10.0.0.16 #patio lights
    - host: 10.0.0.66 #garage spotlight

upnp:
  sensors: true

#input_number:
#  stepper_control:
#    name: Stepper Control
#    initial: 0
#    min: -1000
#    max: 1000
#    step: 1
#    mode: slider

switch:
  - platform: mqtt
    name: office_blinds
    command_topic: "home/office/blinds/set"
    state_topic: "home/office/blinds"
    availability_topic: "home/office/blinds/status"
    payload_on: "OPEN"
    payload_off: "CLOSE"
    state_on: "OPEN"
    state_off: "CLOSE"

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
