homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 298
  unit_system: imperial
  temperature_unit: F
  time_zone: America/New_York
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

# Enables configuration UI
#config:

# Lovelace UI
lovelace:
  mode: yaml

zone:
  - name: Home
    latitude: !secret latitude
    longitude: !secret longitude
    radius: 100
    icon: mdi:home

  - name: Work
    latitude: 39.954605
    longitude: -83.0084049
    icon: mdi:briefcase

default_config:

http:
  # For extra security set this to only accept connections on localhost if NGINX is on the same machine
  # server_host: 127.0.0.1
  # Update this line to be your domain
  base_url: https://home.berkman.co
  use_x_forwarded_for: true
  # You must set the trusted proxy IP address so that Home Assistant will properly accept connections
  # Set this to your NGINX machine IP, or localhost if hosted on the same machine.
  trusted_proxies: 127.0.0.1

frontend:
  themes: !include themes.yaml

discovery:
  #ignore:

# Ecovacs Deebot
ecovacs:
  username: !secret ecovacs_username
  password: !secret ecovacs_password
  country: us
  continent: ww

# IFTTT
ifttt:
  key: !secret ifttt_api_key

# Konnected Security
konnected:
  access_token: !secret konnected_access_token
  api_host: !secret konnected_api_host
  devices:
    - id: !secret konnected_device_id
      host: !secret konnected_device_host
      port: !secret konnected_device_port
      discovery: false
      binary_sensors:
        - zone: 1
          type: door
          name: 'Front Door Sensor'
        - zone: 2
          type: door
          name: 'Garage Door Sensor'
        - zone: 3
          type: door
          name: 'Patio Door Sensor'
        - zone: 4
          type: motion
          name: 'Basement Room Motion Sensor'
        - zone: 5
          type: motion
          name: 'Dining Motion Sensor'
        - zone: 6
          type: motion
          name: 'Kitchen Motion Sensor'
      switches:
        - zone: out
          name: siren

# IKEA Tradfri
tradfri:
  host: 10.0.0.33

# Liftmaster Garage Door Opener
cover:
  - platform: myq
    username: !secret liftmaster_username
    password: !secret liftmaster_password
    type: liftmaster

# Lutron Caseta
lutron_caseta:
  host: 10.0.0.60
  keyfile: lutron/caseta.key
  certfile: lutron/caseta.crt
  ca_certs: lutron/caseta-bridge.crt

# Rachio Smart Irrigation
rachio:
  api_key: !secret rachio_api_key

# Roku
roku:
  - host: 10.0.0.111

sensor:
  - platform: yr
    name: Weather
    forecast: 24
    monitored_conditions:
      - temperature
      - symbol
      - precipitation
      - windSpeed
      - pressure
      - windDirection
      - humidity
      - fog
      - cloudiness
      - lowClouds
      - mediumClouds
      - highClouds
      - dewpointTemperature
  - platform: google_wifi
    name: Google Wifi
  - platform: qnap
    host: 10.0.0.35
    username: !secret qnap_username
    password: !secret qnap_password
    monitored_conditions:
      - status
      - cpu_usage
      - memory_percent_used
      - network_tx
      - volume_percentage_used

light:
  - platform: tplink

automation: !include automations.yaml
group: !include groups.yaml
script: !include scripts.yaml
